# Generated by Django 5.0 on 2023-12-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilemodel',
        ),
    ]
