# Generated by Django 5.0 on 2023-12-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='users',
        ),
    ]
